server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/security_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#
#external:
#  loty:
#    service:
#      url: http://localhost:8081

