server:
  port: 8081

spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5431/flights_db
    username: user
    password: password
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true