package org.example.securityservice.model.enumeration;

public enum IncidentType {
    // Medical emergencies
    MEDICAL_EMERGENCY,
    MEDICAL_FIRST_AID,
    MEDICAL_HEART_ATTACK,
    MEDICAL_STROKE,
    MEDICAL_ALLERGIC_REACTION,

    // Technical issues
    TECHNICAL_POWER_OUTAGE,
    TECHNICAL_EQUIPMENT_FAILURE,
    TECHNICAL_IT_SYSTEM_FAILURE,
    TECHNICAL_COMMUNICATION_FAILURE,
    TECHNICAL_WATER_LEAKAGE,

    // Security threats
    SECURITY_UNAUTHORIZED_ACCESS,
    SECURITY_SUSPICIOUS_PACKAGE,
    SECURITY_TERRORIST_THREAT,
    SECURITY_ASSAULT,
    SECURITY_THEFT,
    SECURITY_CYBER_ATTACK,

    // Fire and hazards
    FIRE_ELECTRICAL,
    FIRE_CHEMICAL,
    FIRE_STRUCTURAL,
    FIRE_VEHICLE,
    HAZARDOUS_MATERIAL_SPILL,

    // Equipment issues
    EQUIPMENT_BAGGAGE_HANDLING,
    EQUIPMENT_ELEVATOR_STUCK,
    EQUIPMENT_ESCALATOR_FAILURE,
    EQUIPMENT_DOOR_MALFUNCTION,
    EQUIPMENT_SECURITY_SCANNER,

    // Weather related
    WEATHER_STORM,
    WEATHER_SNOW_ICE,
    WEATHER_FOG,
    WEATHER_LIGHTNING,

    // Operational issues
    OPERATIONAL_CROWD_CONTROL,
    OPERATIONAL_DELAY_MANAGEMENT,
    OPERATIONAL_NOISE_COMPLAINT,
    OPERATIONAL_PARKING_ISSUE,

    // Transportation
    TRANSPORTATION_VEHICLE_ACCIDENT,
    TRANSPORTATION_RUNWAY_INCIDENT,
    TRANSPORTATION_TAXIWAY_INCIDENT,
    TRANSPORTATION_AIRCRAFT_INCIDENT,

    // Environmental
    ENVIRONMENTAL_BIRD_STRIKE,
    ENVIRONMENTAL_WILDLIFE_INTRUSION,
    ENVIRONMENTAL_POLLUTION,

    // Other
    OTHER_MISCELLANEOUS,
    OTHER_DRILL_EXERCISE,
    OTHER_TEST_ALARM
}